//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agile.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agile.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 任务执行结束事件回调出错。任务key:{0},Name:{1} 的本地化字符串。
        /// </summary>
        internal static string Schedule_AfterTaskRunningEventError {
            get {
                return ResourceManager.GetString("Schedule_AfterTaskRunningEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务执行前事件回调出错。任务key:{0}, Name:{1} 的本地化字符串。
        /// </summary>
        internal static string Schedule_BeforeTaskRunningEventError {
            get {
                return ResourceManager.GetString("Schedule_BeforeTaskRunningEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经有一个不可重入的任务在执行。任务key:{0}, Name:{1} 的本地化字符串。
        /// </summary>
        internal static string Schedule_NonreentrantTaskRunning {
            get {
                return ResourceManager.GetString("Schedule_NonreentrantTaskRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务结束执行。key:{0}, Name:{1},ElapsedTime:{2} 的本地化字符串。
        /// </summary>
        internal static string Schedule_TaskEnd {
            get {
                return ResourceManager.GetString("Schedule_TaskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始执行。key:{0}, Name:{1} 的本地化字符串。
        /// </summary>
        internal static string Schedule_TaskStart {
            get {
                return ResourceManager.GetString("Schedule_TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止时间不可以早于当前时间 的本地化字符串。
        /// </summary>
        internal static string Trigger_EndTimeEarlyThanCurrent {
            get {
                return ResourceManager.GetString("Trigger_EndTimeEarlyThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止时间不可以早于首次触发时间 的本地化字符串。
        /// </summary>
        internal static string Trigger_EndTimeEarlyThanStartTime {
            get {
                return ResourceManager.GetString("Trigger_EndTimeEarlyThanStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat interval must larger than zero 的本地化字符串。
        /// </summary>
        internal static string Trigger_IntervalLargerThanZero {
            get {
                return ResourceManager.GetString("Trigger_IntervalLargerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cannot less than 1, use RepeatInfinite for infinite 的本地化字符串。
        /// </summary>
        internal static string Trigger_RepeatCountNoLessThanOne {
            get {
                return ResourceManager.GetString("Trigger_RepeatCountNoLessThanOne", resourceCulture);
            }
        }
    }
}
